# 开发环境
server:
  port: 8989
  ip: 127.0.0.1

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/cms?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cms
    password: root
