# 生产环境
server:
  port: 9999
  ip: localhost

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/cms-prod?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cms
    password: root
