spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/cms?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cms
    password: cms
    # 选择连接池
    type: com.alibaba.druid.pool.DruidDataSource
# 开启sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id   # 所有实体默认采取该规则
      logic-delete-field: deleted  # 逻辑删除的字段 更新该字段
      logic-not-delete-value: 0 # 未删除的值
      logic-delete-value: 1  # 删除后的值